version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    restart: unless-stopped
    stdin_open: true
    tty: true

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      # Map the Nginx container port 80 to the host port 5173
      - "5173:80"
    restart: unless-stopped
    stdin_open: true
    tty: true
